/**
 * Canonical string type for IRIs/URNs generated by the IRI helpers.
 *
 * Examples:
 * - "urn:req:req-001"
 * - "urn:req:req-001:hdr:0"
 * - "urn:finding:tech%3Areact%3A18"
 *
 * @typedef {string} IriString
 */

/**
 * Stable identifier for HTTP requests.
 *
 * Examples:
 * - "req-001"
 * - "6b5e9a1f-..." (UUID)
 *
 * @typedef {string} RequestId
 */

/**
 * Stable identifier for Finding individuals.
 *
 * Example:
 * - "tech:react:18:CVE-2024-xxxx"
 *
 * @typedef {string} FindingId
 */

/**
 * Index or stable key for evidence entries associated with a Finding.
 *
 * Can be a numeric index or a semantic key.
 *
 * @typedef {number|string} EvidenceIndex
 */

/**
 * Logical key used to identify a Resolver instance.
 *
 * Examples:
 * - "techstack"
 * - "http"
 * - "analyzer"
 *
 * @typedef {string} ResolverKey
 */

/**
 * Stable key used for HTML Tag / Field individuals.
 *
 * Examples:
 * - "https://site/page#script#0"
 * - "https://site/page#script#0:src"
 *
 * @typedef {string} HtmlKey
 */

/**
 * Index or stable key for HTTP header resources (request/response).
 *
 * @typedef {number|string} HeaderIndex
 */

/**
 * Index or stable key for HTTP parameter resources.
 *
 * @typedef {number|string} ParamIndex
 */

module.exports = {};
